const Menu = [
    { id: 1, icon: "payroll", slug: null, path: null, name: "Payroll", dueInfo: 'Last Sent: n/a Next Due: n/a', enable: true, parentId: null },
    { id: 2, icon: "ap", slug: null, path: null, name: "AP", dueInfo: 'Last Sent: n/a Next Due: n/a', enable: true, parentId: null },
    { id: 3, icon: "inventory", slug: null, path: null, name: "Inventory", dueInfo: null, enable: true, parentId: null },
    { id: 4, icon: "sales", slug: null, path: null, name: "Sales", dueInfo: null, enable: true, parentId: null },
    { id: 5, icon: "reportcenter", slug: null, path: null, name: "Report Center", dueInfo: null, enable: true, parentId: null },
    { id: 6, icon: "shipments", slug: 'shipments', path: '/shipments', name: "Shipments", dueInfo: null, enable: true, parentId: null },
    { id: 7, icon: "educationandtraining", slug: 'education_and_training', path: "/education_and_training", name: "Education & Training", dueInfo: null, enable: true, parentId: null },
    { id: 8, icon: "purchasing", slug: null, path: null, name: "Purchasing", dueInfo: null, enable: true, parentId: null },
    { id: 9, icon: "alerts", slug: null, path: null, name: "Alerts & Support", dueInfo: null, enable: true, parentId: null },
    { id: 10, icon: "advanced", slug: null, path: null, name: "Advanced", dueInfo: null, enable: true, parentId: null },
    { id: 11, icon: null, slug: 'payroll', path: '/payroll', name: "Payroll", dueInfo: null, enable: true, parentId: 1 },
    { id: 12, icon: null, slug: 'employees', path: '/employees', name: "Employees", dueInfo: null, enable: true, parentId: 1 },
    { id: 13, icon: null, slug: 'reminders', path: '/reminders', name: "Reminders", dueInfo: null, enable: true, parentId: 1 },
    { id: 14, icon: null, slug: 'pending_employees', path: '/pending_employees', name: "Pending Employees", dueInfo: null, enable: true, parentId: 1 },
    { id: 15, icon: null, slug: '7_shifts_job_code_mapping', path: '/7_shifts_job_code_mapping', name: "7-Shifts Job Code Mapping", dueInfo: null, enable: true, parentId: 1 },
    { id: 16, icon: null, slug: 'account_payable', path: '/account_payable', name: "Account Payable", dueInfo: null, enable: true, parentId: 2 },
    { id: 17, icon: null, slug: 'cash_management', path: '/cash_management', name: "Cash Management", dueInfo: null, enable: true, parentId: 2 },
    { id: 18, icon: null, slug: 'chart_of_accounts', path: '/chart_of_accounts', name: "Chart of Accounts", dueInfo: null, enable: true, parentId: 2 },
    { id: 19, icon: null, slug: null, path: null, name: "Invoicing", dueInfo: null, enable: true, parentId: 2, subTitle: true, subKey: 'invoice' },
    { id: 20, icon: null, slug: 'new_invoice', path: '/new_invoice', name: "New Invoice", dueInfo: null, enable: true, parentId: 2, subKey: 'invoice' },
    { id: 21, icon: null, slug: 'imported_invoices', path: '/imported_invoices', name: "Imported Invoices", dueInfo: null, enable: true, parentId: 2, subKey: 'invoice' },
    { id: 22, icon: null, slug: 'invoices_by_vendor', path: '/invoices_by_vendor', name: "Invoices By Vendor", dueInfo: null, enable: true, parentId: 2, subKey: 'invoice' },
    { id: 23, icon: null, slug: 'invoice_upload', path: '/invoice_upload', name: "Invoice Upload", dueInfo: null, enable: true, parentId: 2, subKey: 'invoice' },
    { id: 24, icon: null, slug: 'invoice_import_setup', path: '/invoice_import_setup', name: "Invoice Import Setup", dueInfo: null, enable: true, parentId: 2, subKey: 'invoice' },
    { id: 25, icon: null, slug: null, path: null, name: "Vendors", dueInfo: null, enable: true, parentId: 2, subTitle: true, subKey: 'vendors' },
    { id: 26, icon: null, slug: 'vendors-unit', path: '/vendors-unit', name: "Vendors - Unit", dueInfo: null, enable: true, parentId: 2, subKey: 'vendors' },
    { id: 27, icon: null, slug: 'vendors_group', path: '/vendors_group', name: "Vendors - Group", dueInfo: null, enable: true, parentId: 2, subKey: 'vendors' },
    { id: 28, icon: null, slug: 'create_tax_or_garn_vendor', path: '/create_tax_or_garn_vendor', name: "Create Tax or Garn Vendor", dueInfo: null, enable: true, parentId: 2, subKey: 'vendors' },
    { id: 29, icon: null, slug: 'manage_tax_and_garn_vendors', path: '/manage_tax_and_garn_vendors', name: "Manage Tax & Garn Vendors", dueInfo: null, enable: true, parentId: 2, subKey: 'vendors' },
    { id: 30, icon: null, slug: 'inventory', path: '/inventory', name: "Inventory", dueInfo: null, enable: true, parentId: 3 },
    { id: 31, icon: null, slug: 'items_unit', path: '/items_unit', name: "Items - Unit", dueInfo: null, enable: true, parentId: 3 },
    { id: 32, icon: null, slug: 'items_group', path: '/items_group', name: "Items - Group", dueInfo: null, enable: true, parentId: 3 },
    { id: 33, icon: null, slug: 'manage_count_sheets', path: '/manage_count_sheets', name: "Manage Count Sheets", dueInfo: null, enable: true, parentId: 3 },
    { id: 34, icon: null, slug: null, path: null, name: "Transfers", dueInfo: null, enable: true, parentId: 3, subTitle: true, subKey: 'transfers' },
    { id: 35, icon: null, slug: 'new_transfer', path: '/new_transfer', name: "New Transfer", dueInfo: null, enable: true, parentId: 3, subKey: 'transfers' },
    { id: 36, icon: null, slug: 'view_all_transfers', path: '/view_all_transfers', name: "View All Transfers", dueInfo: null, enable: true, parentId: 3, subKey: 'transfers' },
    { id: 37, icon: null, slug: null, path: null, name: "Create New", dueInfo: null, enable: true, parentId: 4, subTitle: true, subKey: 'newSales' },
    { id: 38, icon: null, slug: 'cash_paid_out', path: '/cash_paid_out', name: "Cash Paid Out", dueInfo: null, enable: true, parentId: 4, subKey: 'newSales' },
    { id: 39, icon: null, slug: 'misc_deposit', path: '/misc_deposit', name: "Misc Deposit", dueInfo: null, enable: true, parentId: 4, subKey: 'newSales' },
    { id: 40, icon: null, slug: 'create_new_budget', path: '/create_new_budget', name: "Create New Budget", dueInfo: null, enable: true, parentId: 4, subKey: 'newSales' },
    { id: 41, icon: null, slug: null, path: null, name: "Manage Sales", dueInfo: null, enable: true, parentId: 4, subTitle: true, subKey: 'manageSales' },
    { id: 42, icon: null, slug: 'view_curernt_week', path: '/view_curernt_week', name: "View Curernt Week", dueInfo: null, enable: true, parentId: 4, subKey: 'manageSales' },
    { id: 43, icon: null, slug: 'edit_curernt_week', path: '/edit_curernt_week', name: "Edit Current Week", dueInfo: null, enable: true, parentId: 4, subKey: 'manageSales' },
    { id: 44, icon: null, slug: 'past_sales', path: '/past_sales', name: "Past Sales", dueInfo: null, enable: true, parentId: 4, subKey: 'manageSales' },
    { id: 45, icon: null, slug: 'view_budgets', path: '/view_budgets', name: "View Budgets", dueInfo: null, enable: true, parentId: 4, subKey: 'manageSales' },
    { id: 46, icon: null, slug: 'financial_reports', path: '/financial_reports', name: "Financial Reports", dueInfo: null, enable: true, parentId: 5 },
    { id: 47, icon: null, slug: 'report_card', path: '/report_card', name: "Report Card", dueInfo: null, enable: true, parentId: 5 },
    { id: 48, icon: null, slug: 'shift_solutions', path: '/shift_solutions', name: "Shift Solutions", dueInfo: null, enable: true, parentId: 5 },
    { id: 49, icon: null, slug: 'create_new_purchase_order', path: '/create_new_purchase_order', name: "Create New Purchase Order", dueInfo: null, enable: true, parentId: 8 },
    { id: 50, icon: null, slug: 'view_open_purchase_order', path: '/view_open_purchase_order', name: "View Open Purchase Order", dueInfo: null, enable: true, parentId: 8 },
    { id: 51, icon: null, slug: 'submit_purchase_order', path: '/submit_purchase_order', name: "Submit Purchase Order", dueInfo: null, enable: true, parentId: 8 },
    { id: 52, icon: null, slug: null, path: null, name: "Support Tickets", dueInfo: null, enable: true, parentId: 9, subTitle: true, subKey: 'supportTickets' },
    { id: 53, icon: null, slug: 'create_new_support_request', path: '/create_new_support_request', name: "Create New Support Request", dueInfo: null, enable: true, parentId: 9, subKey: 'supportTickets'},
    { id: 54, icon: null, slug: null, path: null, name: "My Support Requests", dueInfo: null, enable: true, parentId: 9, subTitle: true, subKey: 'supportRequests' },
    { id: 55, icon: null, slug: 'awaiting_your_reply_support_requests', path: '/awaiting_your_reply_support_requests', name: "Awaiting Your Reply", dueInfo: null, enable: true, parentId: 9, subKey: 'supportRequests'},
    { id: 56, icon: null, slug: 'open_support_requests', path: '/open_support_requests', name: "Open", dueInfo: null, enable: true, parentId: 9, subKey: 'supportRequests'},
    { id: 57, icon: null, slug: 'recently_solved_support_requests', path: '/recently_solved_support_requests', name: "Recently Solved", dueInfo: null, enable: true, parentId: 9, subKey: 'supportRequests'},
    { id: 58, icon: null, slug: null, path: null, name: "Requests I'm CC'd On", dueInfo: null, enable: true, parentId: 9, subTitle: true, subKey: 'requestIMCC' },
    { id: 59, icon: null, slug: 'awaiting_your_reply_request_imcc', path: '/awaiting_your_reply_request_imcc', name: "Awaiting Your Reply", dueInfo: null, enable: true, parentId: 9, subKey: 'requestIMCC'},
    { id: 60, icon: null, slug: 'open_request_imcc', path: '/open_request_imcc', name: "Open", dueInfo: null, enable: true, parentId: 9, subKey: 'requestIMCC'},
    { id: 61, icon: null, slug: 'recently_solved_request_imcc', path: '/recently_solved_request_imcc', name: "Recently Solved", dueInfo: null, enable: true, parentId: 9, subKey: 'requestIMCC'},
    { id: 62, icon: null, slug: 'closed_support_requests', path: '/closed_support_requests', name: "Closed Support Requests", dueInfo: null, enable: true, parentId: 9, subKey: 'requestIMCC'},
    { id: 63, icon: null, slug: 'archived_support_requests', path: '/archived_support_requests', name: "Archived Support Requests", dueInfo: null, enable: true, parentId: 9, subKey: 'requestIMCC'},
    { id: 64, icon: null, slug: null, path: null, name: "Resources", dueInfo: null, enable: true, parentId: 9, subTitle: true, subKey: 'resources' },
    { id: 65, icon: null, slug: 'all_contact_info', path: '/all_contact_info', name: "All Contact Info", dueInfo: null, enable: true, parentId: 9, subKey: 'resources'},
    { id: 66, icon: null, slug: null, path: null, name: "Conversion", dueInfo: null, enable: true, parentId: 9, subTitle: true, subKey: 'conversion' },
    { id: 67, icon: null, slug: 'manage_conversion', path: '/manage_conversion', name: "Manage Conversion", dueInfo: null, enable: true, parentId: 9, subKey: 'conversion'},
    { id: 68, icon: null, slug: null, path: null, name: "Taxes", dueInfo: null, enable: true, parentId: 9, subTitle: true, subKey: 'taxes' },
    { id: 69, icon: null, slug: 'tax_information', path: '/tax_information', name: "Tax Information", dueInfo: null, enable: true, parentId: 9, subKey: 'taxes'},
    { id: 70, icon: null, slug: null, path: null, name: "Settings", dueInfo: null, enable: true, parentId: 10, subTitle: true, subKey: 'settings' },
    { id: 71, icon: null, slug: 'groups', path: '/groups', name: "Groups", dueInfo: null, enable: true, parentId: 10, subKey: 'settings'},
    { id: 72, icon: null, slug: 'units', path: '/units', name: "Units", dueInfo: null, enable: true, parentId: 10, subKey: 'settings'},
    { id: 73, icon: null, slug: 'users', path: '/users', name: "Users", dueInfo: null, enable: true, parentId: 10, subKey: 'settings'},
    { id: 74, icon: null, slug: null, path: null, name: "Users", dueInfo: null, enable: true, parentId: 10, subTitle: true, subKey: 'users' },
    { id: 75, icon: null, slug: 'log_off', path: '/log_off', name: "Log Off", dueInfo: null, enable: true, parentId: 10, subKey: 'users'},
    { id: 76, icon: null, slug: 'change_password', path: '/change_password', name: "Change Password", dueInfo: null, enable: true, parentId: 10, subKey: 'users'},
]
export default Menu